version: '3.4'

services:
  projecttutorial:
    image: projecttutorial
    build:
      context: Project
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
